name: macOS test build artifact

on:
  workflow_run:
    workflows: ["macOS Qt build (unsigned)"]  # must exactly match the 'name:' above
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-14

    steps:
      - name: Download artifacts from the triggering build run
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          path: artifacts
          # Pattern matches your artifact even with spaces in the name
          pattern: "*unsigned-macOS*"
          merge-multiple: true

      - name: List artifacts (debug)
        run: |
          echo "Artifacts downloaded from run ${{ github.event.workflow_run.id }}"
          ls -R artifacts || true

      - name: Mount DMG (if present) and run headless (robust)
        run: |
          set -euo pipefail
          LOG=runlog.txt

          # 1) Find an app: prefer DMG, else raw .app in artifacts
          DMG=$(find artifacts -name "*.dmg" | head -n1 || true)
          APP=""
          if [ -n "$DMG" ]; then
            echo "DMG=$DMG" | tee -a "$LOG"
            BEFORE="$(ls /Volumes || true)"
            hdiutil attach -nobrowse "$DMG" >>"$LOG" 2>&1
            AFTER="$(ls /Volumes || true)"
            VOL="$(comm -13 <(echo "$BEFORE"|sort) <(echo "$AFTER"|sort) | head -n1)"
            echo "Mounted volume: /Volumes/$VOL" | tee -a "$LOG"
            APP="$(find "/Volumes/$VOL" -maxdepth 1 -type d -name "*.app" | head -n1 || true)"
          fi
          if [ -z "$APP" ]; then
            APP=$(find artifacts -type d -name "*.app" | head -n1 || true)
          fi
          [ -z "$APP" ] && echo "No .app found in DMG or artifacts" | tee -a "$LOG" && exit 1
          echo "Using APP: $APP" | tee -a "$LOG"

          # 2) Figure out the real executable name from Info.plist
          EXE=$(defaults read "$APP/Contents/Info" CFBundleExecutable 2>/dev/null || basename "$APP" .app)
          BIN="$APP/Contents/MacOS/$EXE"
          echo "Resolved executable: $BIN" | tee -a "$LOG"

          # 3) Clear quarantine + ensure executable bit (safe in CI)
          xattr -dr com.apple.quarantine "$APP" || true
          chmod +x "$BIN" || true

          # 4) Extra diagnostics
          echo "---- otool -L ----"   | tee -a "$LOG"
          otool -L "$BIN"           | tee -a "$LOG" || true
          echo "---- codesign -dv ----" | tee -a "$LOG"
          codesign -dv --verbose=4 "$APP" | tee -a "$LOG" || true

          # 5) Run headless with Qt plugin debug enabled
          export QT_QPA_PLATFORM=offscreen
          export QT_DEBUG_PLUGINS=1
          export QT_LOGGING_RULES="qt.serialport.*=true"

          echo "---- $EXE --help ----" | tee -a "$LOG"
          "$BIN" --help               |& tee -a "$LOG" || true

          echo "---- $EXE (headless) ----" | tee -a "$LOG"
          "$BIN"                      |& tee -a "$LOG" || true

          # 6) Detach DMG if we mounted one
          if [ -n "${VOL:-}" ]; then hdiutil detach "/Volumes/$VOL" >>"$LOG" 2>&1 || true; fi

      - name: Upload run log
        uses: actions/upload-artifact@v4
        with:
          name: macOS-headless-run-log
          path: runlog.txt
