name: macOS test build artifact

on:
  workflow_run:
    workflows: ["macOS Qt build (unsigned)"]  # must exactly match the 'name:' above
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-14

    steps:
      - name: Download artifacts from the triggering build run
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          path: artifacts
          # Pattern matches your artifact even with spaces in the name
          pattern: "*unsigned-macOS*"
          merge-multiple: true

      - name: List artifacts (debug)
        run: |
          echo "Artifacts downloaded from run ${{ github.event.workflow_run.id }}"
          ls -R artifacts || true

      - name: Mount DMG (if present) and run headless
        run: |
          set -euo pipefail
          DMG=$(find artifacts -name "*.dmg" | head -n1 || true)
          APP=""
          if [ -n "$DMG" ]; then
            BEFORE="$(ls /Volumes || true)"
            hdiutil attach -nobrowse "$DMG" >/tmp/mount.txt
            AFTER="$(ls /Volumes || true)"
            VOL="$(comm -13 <(echo "$BEFORE"|sort) <(echo "$AFTER"|sort) | head -n1)"
            APP="$(find "/Volumes/$VOL" -maxdepth 1 -type d -name "*.app" | head -n1 || true)"
          fi
          # Fallback: a raw .app in artifacts (if you ever upload it directly)
          if [ -z "$APP" ]; then
            APP=$(find artifacts -type d -name "*.app" | head -n1 || true)
          fi
          [ -z "$APP" ] && echo "No .app found in DMG or artifacts" && exit 1

          BIN="$APP/Contents/MacOS/$(basename "$APP" .app)"
          chmod +x "$BIN" || true
          export QT_QPA_PLATFORM=offscreen
          "$BIN" --help || true
          "$BIN" || true
          otool -L "$BIN" || true
          spctl --assess --type execute --verbose "$APP" || true

          # Detach if mounted
          if [ -n "${VOL:-}" ]; then hdiutil detach "/Volumes/$VOL" || true; fi
