name: macOS Qt build (unsigned)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    env:
      APP_NAME: "Romagnetics FS-404 Companion"
      APP_SUBDIR: "03_Computer Program/src"
      BUILD_TYPE: Release
      QT_VERSION: "6.8.3"

    steps:
      - uses: actions/checkout@v4

      - name: Show workspace
        run: |
          pwd
          ls -la
          ls -la "${{ env.APP_SUBDIR }}" || true

      - name: Install Qt (+ SerialPort)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: desktop
          modules: qtserialport
          cache: true

      - name: Show Qt SerialPort cmake file
        run: |
          set -x
          find "$Qt6_DIR/.." -type f -name "Qt6SerialPortConfig.cmake" | head -n 5

      - name: Configure (arm64)
        run: |
          cmake -S "${{ env.APP_SUBDIR }}" -B build \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_PREFIX_PATH="$Qt6_DIR"

      - name: Build
        run: cmake --build build --config $BUILD_TYPE --parallel

      - name: Locate .app (portable find)
        id: locate
        run: |
          APP_PATH=$(find build -type d -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then echo "No .app found" && exit 1; fi
          echo "path=$APP_PATH" >> $GITHUB_OUTPUT
          echo "Found: $APP_PATH"

      # Ensure offscreen platform plugin is bundled BEFORE making the DMG
      - name: Ensure offscreen platform plugin is present (in build tree)
        run: |
          set -euo pipefail
          APP_DIR="${{ steps.locate.outputs.path }}"
          DEST="$APP_DIR/Contents/PlugIns/platforms"
          # Try a couple likely locations for libqoffscreen.dylib
          CAND1="$Qt6_DIR/../plugins/platforms/libqoffscreen.dylib"
          CAND2="$Qt6_DIR/../../../plugins/platforms/libqoffscreen.dylib"
          PLUG=""
          for C in "$CAND1" "$CAND2"; do
            if [ -f "$C" ]; then PLUG="$C"; break; fi
          done
          if [ -z "$PLUG" ]; then
            echo "ERROR: libqoffscreen.dylib not found near Qt6_DIR"
            echo "Checked:"
            echo "  $CAND1"
            echo "  $CAND2"
            exit 1
          fi
          mkdir -p "$DEST"
          cp -fv "$PLUG" "$DEST/"
          echo "Offscreen plugin copied to: $DEST"
          ls -la "$DEST"

      # Quick headless smoke test from the build tree (uses offscreen)
      - name: Headless smoke test (build tree)
        run: |
          set -euo pipefail
          APP_PATH="${{ steps.locate.outputs.path }}"
          EXE=$(defaults read "$APP_PATH/Contents/Info" CFBundleExecutable 2>/dev/null || basename "$APP_PATH" .app)
          BIN="$APP_PATH/Contents/MacOS/$EXE"
          export QT_QPA_PLATFORM=offscreen
          export QT_DEBUG_PLUGINS=1
          echo "Running: $BIN --help"
          "$BIN" --help || true
          echo "Running: $BIN"
          "$BIN" || true
          echo "---- Linked frameworks ----"
          otool -L "$BIN" || true

      - name: Bundle (macdeployqt, no signing)
        run: |
          macdeployqt "${{ steps.locate.outputs.path }}" \
            -verbose=3 -qmldir="${{ env.APP_SUBDIR }}" -dmg

      # Verify the DMG contains platform plugins (including offscreen we copied)
      - name: Verify platform plugins inside DMG
        run: |
          set -euo pipefail
          DMG=$(ls -1t *.dmg build/*.dmg 2>/dev/null | head -n1)
          echo "DMG=$DMG"
          BEFORE="$(ls /Volumes || true)"
          hdiutil attach -nobrowse "$DMG" >/tmp/mount.txt
          AFTER="$(ls /Volumes || true)"
          VOL="$(comm -13 <(echo "$BEFORE"|sort) <(echo "$AFTER"|sort) | head -n1)"
          echo "Mounted /Volumes/$VOL"
          ls -la "/Volumes/$VOL"/*.app/Contents/PlugIns/platforms || true
          hdiutil detach "/Volumes/$VOL" || true

      - name: Zip the .app
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            "${{ steps.locate.outputs.path }}" "${{ env.APP_NAME }}.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-unsigned-macOS
          # DMG can be in repo root OR in build/, include both; also include the zip
          path: |
            *.dmg
            build/*.dmg
            *.zip
          if-no-files-found: warn
          retention-days: 7
