
Hello Benjamin

Thank you very much for your message!

Regarding shipping
The DHL packet will leave Japan at the beginning of next week.
Once it reaches the United States, it will be updated with the following tracking number: 
9200190328575268075142

I just tested your FS-404. Everything works great but don't hesitate to contact me if you have any issues.

Regarding the mac application.
I have made a Mac version available on GitHub at the following address: 

Because the app is unsigned, the first launch will need a one-time bypass:
Right-click the app → Open → Open (subsequent launches will function normally).

This is normal and will only happen on the first time you open the app.
I tested it with your pedal using a virtual instance but let me know if you can't use the app.

Regarding the next version.
The next version will have the following additions:
*Please note that this version should ship during the first half of 2026.
 I'll send you all the updating steps once the version is ready.

- Toggling back and forth between the pads:
This mode will have two parameters:
Base pad: Choosing the first pad that will be played on
Types: Increase: Starting from the base pad and increasing (going through banks)
       Decrease: Starting from the base pad and decreasing (going through banks)
       Reset: Going back to the first pad
Any type can be added as one of the three switches, so you can have any combination you want.
  
- Configurable kill switch

The kill switch can either be selected as one of the three switch positions or through a configurable timer from 500ms to 5 seconds (configurable in the companion app).

Thanks in advance and best regards!

Romain