name: macOS test prebuilt .app

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["macOS Qt build (unsigned)"]
    types: [completed]

permissions:
  actions: read
  contents: read

jobs:
  test-prebuilt:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-14
    env:
      APP_DIR: "03_Computer Program/Mac_executable/FS-404.app"

    steps:
      - uses: actions/checkout@v4

      - name: Verify .app exists
        run: |
          ls -la "${{ env.APP_DIR }}" || { echo "App not found at ${{ env.APP_DIR }}"; exit 1; }
          ls -la "${{ env.APP_DIR }}/Contents/MacOS" || true

      - name: Install Qt (+ SerialPort)
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.3"
          target: desktop
          modules: qtserialport
          cache: true

      - name: Ensure offscreen plugin is present (copy into committed app)
        run: |
          set -eo pipefail
          APP="${{ env.APP_DIR }}"
          DEST="$APP/Contents/PlugIns/platforms"
          mkdir -p "$DEST"
          PLUGDIR=""
          if command -v qtpaths >/dev/null 2>&1; then
            PLUGDIR="$(qtpaths --plugin-dir || true)"
          elif command -v qmake >/dev/null 2>&1; then
            PLUGDIR="$(qmake -query QT_INSTALL_PLUGINS || true)"
          fi
          PLUG=""
          [ -n "$PLUGDIR" ] && PLUG="$PLUGDIR/platforms/libqoffscreen.dylib"
          if [ ! -f "${PLUG:-/nonexistent}" ]; then
            PLUG="$(find "$RUNNER_TEMP" "$GITHUB_WORKSPACE/Qt" -maxdepth 6 -name 'libqoffscreen.dylib' 2>/dev/null | head -n1 || true)"
          fi
          if [ -n "$PLUG" ] && [ -f "$PLUG" ]; then
            cp -fv "$PLUG" "$DEST/"
            echo "Copied offscreen plugin from: $PLUG"
          else
            echo "WARNING: libqoffscreen.dylib not found; will still try with cocoa."
          fi

      - name: Headless --help (15s timeout) + diagnostics
        run: |
          set -eo pipefail
          LOG=runlog.txt
          APP="${{ env.APP_DIR }}"
          EXE=$(defaults read "$APP/Contents/Info" CFBundleExecutable 2>/dev/null || basename "$APP" .app)
          BIN="$APP/Contents/MacOS/$EXE"
          chmod +x "$BIN" || true

          echo "---- otool -L ----" | tee "$LOG"
          otool -L "$BIN" 2>&1 | tee -a "$LOG" || true

          export QT_QPA_PLATFORM=offscreen
          export QT_DEBUG_PLUGINS=1
          export QT_LOGGING_RULES="qt.serialport.*=true"

          echo "---- $EXE --help (15s timeout) ----" | tee -a "$LOG"
          python3 -c 'import os,subprocess,threading; bin=os.environ.get("BIN") or "'"$BIN"'"; p=subprocess.Popen([bin,"--help"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True); t=threading.Timer(15, p.kill); t.start(); out=p.communicate()[0]; print(out if out else "");' 2>&1 | tee -a "$LOG"

          echo "---- $EXE (headless, 20s timeout) ----" | tee -a "$LOG"
          python3 -c 'import os,subprocess,threading,time; bin=os.environ.get("BIN") or "'"$BIN"'"; p=subprocess.Popen([bin], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True); start=time.time(); t=threading.Timer(20, p.kill); t.start(); out=p.communicate()[0]; print(out if out else "");  print("TIMEOUT: app did not exit in 20s") if time.time()-start>=20 else None' 2>&1 | tee -a "$LOG"

      - name: Upload run log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macOS-headless-run-log
          path: runlog.txt
